--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/IceCruelStuff/ServerCore
branches:
- master
projects:
  ServerCore:
    path: ""
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^1.3
...
